---
abstract: 'collection of blocks for processing Czech'
author:
  - 'Treex team <treex@ufal.mff.cuni.cz>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
  File::ShareDir::Install: '0.06'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Treex-CS
requires:
  Moose: '0'
  Treex::Block::W2A::ParseMSTperl: '0'
  Treex::Block::W2A::TagMorphoDiTa: '0'
  Treex::Block::W2A::Tokenize: '0'
  Treex::Core::Block: '0'
  Treex::Core::Common: '0'
  Treex::Tool::Lexicon::CS: '0'
  Treex::Unilang: '0'
  Ufal::MorphoDiTa: '0'
  strict: '0'
  utf8: '0'
  warnings: '0'
version: '0.13100'
